<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Content</title>
    <link rel="stylesheet" href="stylec.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
     integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" 
     crossorigin="anonymous">
</head>
<body>

<nav>
        <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="fas fa-bars"></i>
            </label>
            <label class="logo">IT-Dunia</label>
        <ul>
            <li><a class="active" href="index.php">Home</a></li>
            <li><a href="search.php">Search</a></li>
            <li><a href="upload.php">Upload Content</a></li>
            <li><a href="registration.php">Registration</a></li>                
            <li><a href="#">About Us</a></li>
        </ul>
        </nav>


<div class="container">
    <div class="content">
        <img src="7.jpg" alt="lights">
        <div class="wrapper">
            <h1>This Computer Predicts Your Thoughts</h1>
            <p>Hunberg alex</p>
            <section class="block">
                <p>By monitoring brain function, computers can be made imagine what a person is thinking of and present the results as images. The technique can be utilized in psychology and cognitive neuroscience, as well as supporting human creativity.

Researchers at the University of Helsinki have developed a technique in which a computer models visual perception by monitoring human brain signals. In a way, it is as if the computer tries to imagine what a human is thinking about. As a result of this imagining, the computer is able to produce entirely new information, such as fictional images that were never before seen.

The technique is based on a novel brain-computer interface. Previously, similar brain-computer interfaces have been able to perform one-way communication from brain to computer, such as spell individual letters or move a cursor.

As far as is known, the new study is the first where both the computer’s presentation of the information and brain signals were modeled simultaneously using artificial intelligence methods. Images that matched the visual characteristics that participants were focusing on were generated through interaction between human brain responses and a generative neural network.

The study was published in the Scientific Reports journal on September 7, 2020. Scientific Reports is an online multidisciplinary, open-access journal from the publishers of Nature.</p>
                <p>The researchers call this method neuroadaptive generative modeling. A total of 31 volunteers participated in a study that evaluated the effectiveness of the technique. Participants were shown hundreds of AI-generated images of diverse-looking people while their EEG was recorded.

The subjects were asked to concentrate on certain features, such as faces that looked old or were smiling. While looking at a rapidly presented series of face images, the EEGs of the subjects were fed to a neural network, which inferred whether any image was detected by the brain as matching what the subjects were looking for.

Based on this information, the neural network adapted its estimation as to what kind of faces people were thinking of. Finally, the images generated by the computer were evaluated by the participants and they nearly perfectly matched with the features the participants were thinking of. The accuracy of the experiment was 83 percent.

“The technique combines natural human responses with the computer’s ability to create new information. In the experiment, the participants were only asked to look at the computer-generated images.  The computer, in turn, modeled the images displayed and the human reaction toward the images by using human brain responses. From this, the computer can create an entirely new image that matches the user’s intention,” says Tuukka Ruotsalo, Academy of Finland Research Fellow at the University of Helsinki, Finland, and Associate Professor at the University of Copenhagen, Denmark.</p>

            </section>

        </div>
 
    </div>

</div>










<div class="footer">
    <div class="inner-footer">

        <div class="footer-items">
            <h1>IT News</h1>
            <p>Content itself is what the user derives value from....</p>

        </div>

        <div class="footer-items">
            <h1>Quick Links</h1>
            <div class="border"></div>
                <ul>
                    <a href=""><li>Home</li></a>
                    <a href=""><li>Upload</li></a>
                    <a href=""><li>Search</li></a>
                    <a href=""><li>Sign-Up</li></a>
                </ul>

        </div>
        <div class="footer-items">
            <h1>Tutorials</h1>
            <div class="border"></div>
                <ul>
                    <a href=""><li>IT Business</li></a>
                    <a href=""><li>Game</li></a>
                    <a href=""><li>Technology</li></a>
                    <a href=""><li>Gadget</li></a>
                </ul>

        </div>

        <div class="footer-items">
            <h1>Contact Us</h1>
            <div class="border"></div>
                <ul>
                    <li><i class="fa fa-map-marker" aria-hidden="true"></i>15/2, Mohammadpur, Dhaka-1207</li>
                    <li><i class="fa fa-phone" aria-hidden="true"></i>+8801844668069</li>
                    <li><i class="fa fa-envelope" aria-hidden="true"></i>support@itdunia.com</li>
                </ul>
                <div class="social-media">
                    <a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href=""><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                </div>

        </div>
    </div>
    <div class="footer-bottom">
        Copyright &copy; Computers & Codes 2020. All rights reserved.

    </div>


    </div>

</div>
    
        
    
</body>
</html>